### ISSUE TITLE
many errors

### ISSUE THREAD

**Issue by PandoricGalaxy** [yuta-belmont/metamask_bf#2]
![image](https://user-images.githubusercontent.com/86944806/163709858-10432b82-6637-474a-a747-59830c4bb817.png)
![image](https://user-images.githubusercontent.com/86944806/163709897-c22a8c5b-bf96-48d3-8c39-394e83f52632.png)
Chrome and Driver version 100
python version 3.1.4

**Comment by PandoricGalaxy** [comment]
pls help?

**Comment by UmerFarooqBiomedical** [comment]
How did you fix it?
